/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiChatsRouteImport } from './routes/api/chats'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as ApiProvidersRouteImport } from './routes/api/providers'
import { Route as ApiPublicConfigRouteImport } from './routes/api/public-config'
import { Route as ApiSetupRouteImport } from './routes/api/setup'
import { Route as SettingsMcpRouteImport } from './routes/settings.mcp'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as ApiAdminConfigRouteImport } from './routes/api/admin/config'
import { Route as ApiAdminOidcTestRouteImport } from './routes/api/admin/oidc-test'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMcpTestRouteImport } from './routes/api/mcp.test'
import { Route as ApiMcpTrustRouteImport } from './routes/api/mcp.trust'
import { Route as ApiProvidersTestRouteImport } from './routes/api/providers.test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatsRoute = ApiChatsRouteImport.update({
  id: '/api/chats',
  path: '/api/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvidersRoute = ApiProvidersRouteImport.update({
  id: '/api/providers',
  path: '/api/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConfigRoute = ApiPublicConfigRouteImport.update({
  id: '/api/public-config',
  path: '/api/public-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupRoute = ApiSetupRouteImport.update({
  id: '/api/setup',
  path: '/api/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMcpRoute = SettingsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const ApiAdminConfigRoute = ApiAdminConfigRouteImport.update({
  id: '/api/admin/config',
  path: '/api/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOidcTestRoute = ApiAdminOidcTestRouteImport.update({
  id: '/api/admin/oidc-test',
  path: '/api/admin/oidc-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpTestRoute = ApiMcpTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ApiMcpRoute,
} as any)
const ApiMcpTrustRoute = ApiMcpTrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => ApiMcpRoute,
} as any)
const ApiProvidersTestRoute = ApiProvidersTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ApiProvidersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/settings': typeof SettingsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/chats': typeof ApiChatsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/models': typeof ApiModelsRoute
  '/api/providers': typeof ApiProvidersRouteWithChildren
  '/api/public-config': typeof ApiPublicConfigRoute
  '/api/setup': typeof ApiSetupRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/api/admin/config': typeof ApiAdminConfigRoute
  '/api/admin/oidc-test': typeof ApiAdminOidcTestRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mcp/test': typeof ApiMcpTestRoute
  '/api/mcp/trust': typeof ApiMcpTrustRoute
  '/api/providers/test': typeof ApiProvidersTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/settings': typeof SettingsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/chats': typeof ApiChatsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/models': typeof ApiModelsRoute
  '/api/providers': typeof ApiProvidersRouteWithChildren
  '/api/public-config': typeof ApiPublicConfigRoute
  '/api/setup': typeof ApiSetupRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/api/admin/config': typeof ApiAdminConfigRoute
  '/api/admin/oidc-test': typeof ApiAdminOidcTestRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mcp/test': typeof ApiMcpTestRoute
  '/api/mcp/trust': typeof ApiMcpTrustRoute
  '/api/providers/test': typeof ApiProvidersTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/settings': typeof SettingsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/chats': typeof ApiChatsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/models': typeof ApiModelsRoute
  '/api/providers': typeof ApiProvidersRouteWithChildren
  '/api/public-config': typeof ApiPublicConfigRoute
  '/api/setup': typeof ApiSetupRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/api/admin/config': typeof ApiAdminConfigRoute
  '/api/admin/oidc-test': typeof ApiAdminOidcTestRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mcp/test': typeof ApiMcpTestRoute
  '/api/mcp/trust': typeof ApiMcpTrustRoute
  '/api/providers/test': typeof ApiProvidersTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chat'
    | '/settings'
    | '/api/chat'
    | '/api/chats'
    | '/api/health'
    | '/api/mcp'
    | '/api/me'
    | '/api/models'
    | '/api/providers'
    | '/api/public-config'
    | '/api/setup'
    | '/settings/mcp'
    | '/settings/profile'
    | '/api/admin/config'
    | '/api/admin/oidc-test'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/mcp/test'
    | '/api/mcp/trust'
    | '/api/providers/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/chat'
    | '/settings'
    | '/api/chat'
    | '/api/chats'
    | '/api/health'
    | '/api/mcp'
    | '/api/me'
    | '/api/models'
    | '/api/providers'
    | '/api/public-config'
    | '/api/setup'
    | '/settings/mcp'
    | '/settings/profile'
    | '/api/admin/config'
    | '/api/admin/oidc-test'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/mcp/test'
    | '/api/mcp/trust'
    | '/api/providers/test'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chat'
    | '/settings'
    | '/api/chat'
    | '/api/chats'
    | '/api/health'
    | '/api/mcp'
    | '/api/me'
    | '/api/models'
    | '/api/providers'
    | '/api/public-config'
    | '/api/setup'
    | '/settings/mcp'
    | '/settings/profile'
    | '/api/admin/config'
    | '/api/admin/oidc-test'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/mcp/test'
    | '/api/mcp/trust'
    | '/api/providers/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChatRoute: typeof ChatRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiChatsRoute: typeof ApiChatsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMcpRoute: typeof ApiMcpRouteWithChildren
  ApiMeRoute: typeof ApiMeRoute
  ApiModelsRoute: typeof ApiModelsRoute
  ApiProvidersRoute: typeof ApiProvidersRouteWithChildren
  ApiPublicConfigRoute: typeof ApiPublicConfigRoute
  ApiSetupRoute: typeof ApiSetupRoute
  ApiAdminConfigRoute: typeof ApiAdminConfigRoute
  ApiAdminOidcTestRoute: typeof ApiAdminOidcTestRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chats': {
      id: '/api/chats'
      path: '/api/chats'
      fullPath: '/api/chats'
      preLoaderRoute: typeof ApiChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/providers': {
      id: '/api/providers'
      path: '/api/providers'
      fullPath: '/api/providers'
      preLoaderRoute: typeof ApiProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-config': {
      id: '/api/public-config'
      path: '/api/public-config'
      fullPath: '/api/public-config'
      preLoaderRoute: typeof ApiPublicConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup': {
      id: '/api/setup'
      path: '/api/setup'
      fullPath: '/api/setup'
      preLoaderRoute: typeof ApiSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/mcp': {
      id: '/settings/mcp'
      path: '/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof SettingsMcpRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/api/admin/config': {
      id: '/api/admin/config'
      path: '/api/admin/config'
      fullPath: '/api/admin/config'
      preLoaderRoute: typeof ApiAdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/oidc-test': {
      id: '/api/admin/oidc-test'
      path: '/api/admin/oidc-test'
      fullPath: '/api/admin/oidc-test'
      preLoaderRoute: typeof ApiAdminOidcTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/test': {
      id: '/api/mcp/test'
      path: '/test'
      fullPath: '/api/mcp/test'
      preLoaderRoute: typeof ApiMcpTestRouteImport
      parentRoute: typeof ApiMcpRoute
    }
    '/api/mcp/trust': {
      id: '/api/mcp/trust'
      path: '/trust'
      fullPath: '/api/mcp/trust'
      preLoaderRoute: typeof ApiMcpTrustRouteImport
      parentRoute: typeof ApiMcpRoute
    }
    '/api/providers/test': {
      id: '/api/providers/test'
      path: '/test'
      fullPath: '/api/providers/test'
      preLoaderRoute: typeof ApiProvidersTestRouteImport
      parentRoute: typeof ApiProvidersRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsMcpRoute: typeof SettingsMcpRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsMcpRoute: SettingsMcpRoute,
  SettingsProfileRoute: SettingsProfileRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ApiMcpRouteChildren {
  ApiMcpTestRoute: typeof ApiMcpTestRoute
  ApiMcpTrustRoute: typeof ApiMcpTrustRoute
}

const ApiMcpRouteChildren: ApiMcpRouteChildren = {
  ApiMcpTestRoute: ApiMcpTestRoute,
  ApiMcpTrustRoute: ApiMcpTrustRoute,
}

const ApiMcpRouteWithChildren =
  ApiMcpRoute._addFileChildren(ApiMcpRouteChildren)

interface ApiProvidersRouteChildren {
  ApiProvidersTestRoute: typeof ApiProvidersTestRoute
}

const ApiProvidersRouteChildren: ApiProvidersRouteChildren = {
  ApiProvidersTestRoute: ApiProvidersTestRoute,
}

const ApiProvidersRouteWithChildren = ApiProvidersRoute._addFileChildren(
  ApiProvidersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChatRoute: ChatRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiChatsRoute: ApiChatsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMcpRoute: ApiMcpRouteWithChildren,
  ApiMeRoute: ApiMeRoute,
  ApiModelsRoute: ApiModelsRoute,
  ApiProvidersRoute: ApiProvidersRouteWithChildren,
  ApiPublicConfigRoute: ApiPublicConfigRoute,
  ApiSetupRoute: ApiSetupRoute,
  ApiAdminConfigRoute: ApiAdminConfigRoute,
  ApiAdminOidcTestRoute: ApiAdminOidcTestRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
